services:
  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
    command:
      - --transport=sse
      - --servers=zerodha-kite,duckduckgo
      - --port=8080
      - --verbose=true
      - --config=/config/gateway.yaml
    networks:
      - mcp-gateway-network
    env_file:
      - .env

  zerodha-kite:
    image: mcp/zerodha-kite:latest
    container_name: zerodha-kite
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # These are the key variables needed to switch from stdio to HTTP/SSE mode
      - APP_MODE=hybrid          # Supports both /mcp and /sse endpoints
      - APP_HOST=0.0.0.0        # Bind to all interfaces so gateway can reach it
      - APP_PORT=8080           # Port to serve on inside container
    networks:
      - mcp-gateway-network

  duckduckgo:
    image: mcp/duckduckgo:latest
    container_name: duckduckgo
    restart: unless-stopped
    networks:
      - mcp-gateway-network

networks:
  mcp-gateway-network:
    driver: bridge
