version: '3.8'

services:
  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
    command:
      - --transport=sse
      - --servers=nasdaq-data-link
      - --port=8080
      - --verbose=true
      - --config=/config/gateway.yaml
    environment:
      - NASDAQ_DATA_LINK_API_KEY=${NASDAQ_API_KEY}
      # Uncomment and add if needed:
      # - KITE_API_KEY=${KITE_API_KEY}
      # - KITE_API_SECRET=${KITE_API_SECRET}
    # secrets:
    #   - source: my_secret

  nasdaq-mcp:
    image: mcp/nasdaq-data-link:latest
    environment:
      - NASDAQ_DATA_LINK_API_KEY=${NASDAQ_API_KEY}
    ports:
      - "8081:8080"
# secrets:
#   my_secret:
#     file: ./nasdaq_data_link_api_key.txt
