servers:
  nasdaq-data-link:
    url: "http://nasdaq-mcp:8080/sse"   # Use the Docker service name 'nasdaq-mcp' and port
    secret_env: NASDAQ_DATA_LINK_API_KEY # Environment variable for the API key if needed

transport:
  type: sse
  port: 8080   # Port the gateway listens on for SSE connections

security:
  verify_signatures: true   # Security option for verifying request signatures
