servers:
  # Remove zerodha-kite URL - gateway handles it in stdio mode
  duckduckgo:
    url: http://duckduckgo:8080/sse

transport:
  type: sse
  port: 8080

security:
  verify_signatures: true
